# Variables
substitutions:
  plug_name: bw6
  current_res: "0.00222"
  voltage_div: "965"

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp8285
  esp8266_restore_from_flash: true

wifi:
  ssid: "matrix"
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${plug_name} Fallback"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Common includes
binary_sensor: !include _includes/bw_binary_sensors.yaml
switch: !include _includes/bw_switches.yaml
sensor: !include _includes/bw_sensors.yaml

# FW
text_sensor:
  - platform: version
    name: ${plug_name}_fw_version
